sonar.projectKey=frontend
sonar.projectName=fronetend



# Source configuration
sonar.sources=src
#sonar.exclusions=node_modules/**,coverage/**,**/*.spec.js,**/__tests__/**

# Language & encoding
sonar.language=js
sonar.sourceEncoding=UTF-8

# Coverage report (if available)
# sonar.javascript.lcov.reportPaths=coverage/lcov.info

# SonarQube server details
#sonar.host.url=http://65.0.139.12:9000
